### ISSUE TITLE
Not able to compile on ROS lunar with ubuntu 16.04

### ISSUE THREAD

**Issue by varsha-devi** [sfotiadis/hdetect#5]
I am trying to compile your code. I have installed ROS lunar and opencv 2.9.x installed. Inside the catkin workspace, I am running the command catkin_make it is giving me following error 
![Screenshot from 2019-03-28 10-28-18](https://user-images.githubusercontent.com/45758791/55146131-46440680-5144-11e9-94cc-4a37b2947353.png)
![Screenshot from 2019-03-28 10-28-25](https://user-images.githubusercontent.com/45758791/55146132-46dc9d00-5144-11e9-8b00-8d17b2eabc15.png)

please help me in compiling the project I need help from your code.

**Comment by marioney** [comment]
Hi.

I'm sorry. The code is not yet available for ROS lunar. We are just
adapting it to ROS kinetic.

I'll let you know when the upgrade to Lunar is available.

Regards,

Mario

Le jeu. 28 mars 2019 à 10:30, varshadevi2018 <notifications@github.com> a
écrit :

**Comment by FooKii** [comment]
Hi, i'm new to ROS and trying to use your package in Kinetic, Is there a kinetic version now? or i need to change something myself?
Regardsm

Fook

**Comment by marioney** [comment]
Hi,

Please give me a couple days to give you a proper answer on this.  I'll have to check if there's a version ready for Kinect

**Comment by marioney** [comment]
Hi, 


I've created two branchs, for [Kinetic](https://github.com/stathius/hdetect/tree/kinetic-devel) and [melodic](https://github.com/stathius/hdetect/tree/melodic-devel)

> Hi, i'm new to ROS and trying to use your package in Kinetic, Is there a kinetic version now? or i need to change something myself?

They should work, can you test them and let us know?

**Comment by FooKii** [comment]
Hey @marioney ,  
thx for the update. I can install it successfully. Only i had to install libnewmat mannually cause rosdep gives 
```Cannot locate rosdep definition for [libnewmat10-dev]```
BR,
Fooki

**Comment by marioney** [comment]
That's great!
For the dependency, you need to re-run `rosdep update` to get an updated version.

I'm closing this. Please open a new issue if you get any other error.
