### ISSUE TITLE
Cannot build the package

### ISSUE THREAD

**Issue by dharanish-nh** [sfotiadis/hdetect#6]
I am using ROS Melodic and Ubuntu 18. I found out the some of the functions used have different format now. 

<pre><font color="#EF2929"><b>Errors</b></font>    <font color="#CC0000"> &lt;&lt;</font> <font color="#06989A">hdetect</font>:<font color="#3465A4">make</font> <font color="#EF2929"><b>/home/akhilesh/catkin_ws/logs/hdetect/build.make.006.log</b></font>                                                        
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:14:11:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cv::TrainData</b>’ has not been declared
 using cv::<font color="#EF2929"><b>TrainData</b></font>;
           <font color="#EF2929"><b>^~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:15:11:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cv::Boost</b>’ has not been declared
 using cv::<font color="#EF2929"><b>Boost</b></font>;
           <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:16:11:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cv::BoostParams</b>’ has not been declared
 using cv::<font color="#EF2929"><b>BoostParams</b></font>;
           <font color="#EF2929"><b>^~~~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:</b> In function ‘<b>int main(int, char**)</b>’:
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:42:5:</b> <font color="#EF2929"><b>error: </b></font>‘<b>TrainData</b>’ was not declared in this scope
     <font color="#EF2929"><b>TrainData</b></font> cvml;
     <font color="#EF2929"><b>^~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:42:5:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative:
In file included from <b>/usr/include/opencv2/opencv.hpp:74:0</b>,
                 from <b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:7</b>:
<b>/usr/include/opencv2/ml.hpp:137:20:</b> <font color="#34E2E2"><b>note: </b></font>  ‘<b>cv::ml::TrainData</b>’
 class CV_EXPORTS_W <font color="#34E2E2"><b>TrainData</b></font>
                    <font color="#34E2E2"><b>^~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:45:5:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cvml</b>’ was not declared in this scope
     <font color="#EF2929"><b>cvml</b></font>.read_csv(read_path.c_str());
     <font color="#EF2929"><b>^~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:45:5:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>cvCmp</b>’
     <font color="#34E2E2"><b>cvml</b></font>.read_csv(read_path.c_str());
     <font color="#34E2E2"><b>^~~~</b></font>
     <font color="#4E9A06">cvCmp</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:50:29:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CV_VAR_CATEGORICAL</b>’ was not declared in this scope
     cvml.change_var_type(0, <font color="#EF2929"><b>CV_VAR_CATEGORICAL</b></font>);
                             <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~</b></font>
In file included from <b>/home/akhilesh/catkin_ws/src/hdetect/include/hdetect/lib/object_tracking.hpp:13:0</b>,
                 from <b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/object_tracking.cpp:1</b>:
<b>/home/akhilesh/catkin_ws/src/hdetect/include/hdetect/lib/detector.hpp:141:2:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CvBoost</b>’ does not name a type; did you mean ‘<b>CvFont</b>’?
  <font color="#EF2929"><b>CvBoost</b></font> boost;
  <font color="#EF2929"><b>^~~~~~~</b></font>
  <font color="#4E9A06">CvFont</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:50:29:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>CV_RETR_EXTERNAL</b>’
     cvml.change_var_type(0, <font color="#34E2E2"><b>CV_VAR_CATEGORICAL</b></font>);
                             <font color="#34E2E2"><b>^~~~~~~~~~~~~~~~~~</b></font>
                             <font color="#4E9A06">CV_RETR_EXTERNAL</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:102:5:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CvTrainTestSplit</b>’ was not declared in this scope
     <font color="#EF2929"><b>CvTrainTestSplit</b></font> cvtts(portion, true);
     <font color="#EF2929"><b>^~~~~~~~~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:105:32:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cvtts</b>’ was not declared in this scope
     cvml.set_train_test_split(&amp;<font color="#EF2929"><b>cvtts</b></font>);
                                <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:105:32:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>cvAbs</b>’
     cvml.set_train_test_split(&amp;<font color="#34E2E2"><b>cvtts</b></font>);
                                <font color="#34E2E2"><b>^~~~~</b></font>
                                <font color="#4E9A06">cvAbs</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:111:5:</b> <font color="#EF2929"><b>error: </b></font>‘<b>Boost</b>’ was not declared in this scope
     <font color="#EF2929"><b>Boost</b></font> boost;
     <font color="#EF2929"><b>^~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:111:5:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative:
In file included from <b>/usr/include/opencv2/opencv.hpp:74:0</b>,
                 from <b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:7</b>:
<b>/usr/include/opencv2/ml.hpp:1182:20:</b> <font color="#34E2E2"><b>note: </b></font>  ‘<b>cv::ml::Boost</b>’
 class CV_EXPORTS_W <font color="#34E2E2"><b>Boost</b></font> : public DTrees
                    <font color="#34E2E2"><b>^~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:114:25:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     bool success = boost<font color="#EF2929"><b>.</b></font>train(&amp;cvml, BoostParams(CvBoost::REAL, 100, 0, 1, false, 0), false);
                         <font color="#EF2929"><b>^</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:114:51:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CvBoost</b>’ has not been declared
     bool success = boost.train(&amp;cvml, BoostParams(<font color="#EF2929"><b>CvBoost</b></font>::REAL, 100, 0, 1, false, 0), false);
                                                   <font color="#EF2929"><b>^~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:114:39:</b> <font color="#EF2929"><b>error: </b></font>‘<b>BoostParams</b>’ was not declared in this scope
     bool success = boost.train(&amp;cvml, <font color="#EF2929"><b>BoostParams</b></font>(CvBoost::REAL, 100, 0, 1, false, 0), false);
                                       <font color="#EF2929"><b>^~~~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:131:22:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     float fl1 = boost<font color="#EF2929"><b>.</b></font>calc_error(&amp;cvml, CV_TRAIN_ERROR, &amp;train_responses);
                      <font color="#EF2929"><b>^</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:131:41:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CV_TRAIN_ERROR</b>’ was not declared in this scope
     float fl1 = boost.calc_error(&amp;cvml, <font color="#EF2929"><b>CV_TRAIN_ERROR</b></font>, &amp;train_responses);
                                         <font color="#EF2929"><b>^~~~~~~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:131:41:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>CV_ERROR</b>’
     float fl1 = boost.calc_error(&amp;cvml, <font color="#34E2E2"><b>CV_TRAIN_ERROR</b></font>, &amp;train_responses);
                                         <font color="#34E2E2"><b>^~~~~~~~~~~~~~</b></font>
                                         <font color="#4E9A06">CV_ERROR</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:133:22:</b> <font color="#EF2929"><b>error: </b></font>expected ‘<b>;</b>’ before ‘<b>cvtts2</b>’
     CvTrainTestSplit <font color="#EF2929"><b>cvtts2</b></font>(0.5f, true);
                      <font color="#EF2929"><b>^~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:134:32:</b> <font color="#EF2929"><b>error: </b></font>‘<b>cvtts2</b>’ was not declared in this scope
     cvml.set_train_test_split(&amp;<font color="#EF2929"><b>cvtts2</b></font>);
                                <font color="#EF2929"><b>^~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:134:32:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>cvPtr2D</b>’
     cvml.set_train_test_split(&amp;<font color="#34E2E2"><b>cvtts2</b></font>);
                                <font color="#34E2E2"><b>^~~~~~</b></font>
                                <font color="#4E9A06">cvPtr2D</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:137:22:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     float fl2 = boost<font color="#EF2929"><b>.</b></font>calc_error(&amp;cvml, CV_TEST_ERROR, &amp;test_responses);
                      <font color="#EF2929"><b>^</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:137:41:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CV_TEST_ERROR</b>’ was not declared in this scope
     float fl2 = boost.calc_error(&amp;cvml, <font color="#EF2929"><b>CV_TEST_ERROR</b></font>, &amp;test_responses);
                                         <font color="#EF2929"><b>^~~~~~~~~~~~~</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:137:41:</b> <font color="#34E2E2"><b>note: </b></font>suggested alternative: ‘<b>CV_ERROR</b>’
     float fl2 = boost.calc_error(&amp;cvml, <font color="#34E2E2"><b>CV_TEST_ERROR</b></font>, &amp;test_responses);
                                         <font color="#34E2E2"><b>^~~~~~~~~~~~~</b></font>
                                         <font color="#4E9A06">CV_ERROR</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/trainLaser.cpp:144:10:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     boost<font color="#EF2929"><b>.</b></font>save(write_path.c_str(), &quot;boost&quot;);
          <font color="#EF2929"><b>^</b></font>
make[2]: *** [CMakeFiles/trainLaser.dir/src/trainLaser.cpp.o] Error 1
make[1]: *** [CMakeFiles/trainLaser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ObjectTracking.dir/src/lib/object_tracking.cpp.o] Error 1
make[1]: *** [CMakeFiles/ObjectTracking.dir/all] Error 2
In file included from <b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/detector.cpp:1:0</b>:
<b>/home/akhilesh/catkin_ws/src/hdetect/include/hdetect/lib/detector.hpp:141:2:</b> <font color="#EF2929"><b>error: </b></font>‘<b>CvBoost</b>’ does not name a type; did you mean ‘<b>CvFont</b>’?
  <font color="#EF2929"><b>CvBoost</b></font> boost;
  <font color="#EF2929"><b>^~~~~~~</b></font>
  <font color="#4E9A06">CvFont</font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/detector.cpp:</b> In constructor ‘<b>detector::detector()</b>’:
<b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/detector.cpp:41:10:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     boost<font color="#EF2929"><b>.</b></font>load(boost_xml.c_str() , &quot;boost&quot;);
          <font color="#EF2929"><b>^</b></font>
<b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/detector.cpp:</b> In member function ‘<b>void detector::classifyLaser(std_msgs::Float32MultiArray&amp;, float&amp;)</b>’:
<b>/home/akhilesh/catkin_ws/src/hdetect/src/lib/detector.cpp:250:18:</b> <font color="#EF2929"><b>error: </b></font>expected primary-expression before ‘<b>.</b>’ token
     probs = boost<font color="#EF2929"><b>.</b></font>predict(lFeatures, Mat(), Range::all(), false, true);
                  <font color="#EF2929"><b>^</b></font>
make[2]: *** [CMakeFiles/detector.dir/src/lib/detector.cpp.o] Error 1
make[1]: *** [CMakeFiles/detector.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by marioney** [comment]
Hi,

Can you make sure that you're working on the [melodic-devel](https://github.com/stathius/hdetect/tree/melodic-devel) branch.

Please checkout that branch and let us know if you have the same errors?

**Comment by dharanish-nh** [comment]
I had downloaded the wrong files .
Thanks for replying.
