### ISSUE TITLE
How can i implement this on intel realsense camera?

### ISSUE THREAD

**Issue by dharanish-nh** [sfotiadis/hdetect#7]
I am using Intel real sense camera to simulate laser data via pointcloud conversion. I would like to test your project in real time. I did change the topic names in visualiseRT.launch file but i did not get proper result. I think i may have missed some steps in order to do that. Can you please suggest how it is supposed to be implemented. @marioney

**Comment by marioney** [comment]
Hi,

If you want to run the process on-line, you need to use - and update the values of - the [recognizeRT.launch](https://github.com/stathius/hdetect/blob/melodic-devel/launches/recognizeRT.launch)

You of course, need to update the camera calibration file (I think the real sense camera has a calibration file by default) and update the values of topics and the other parameters.

Please try that and let me know how it goes for you.

**Comment by stathius** [comment]
@marioney Sorry to interrupt but buddy, I'm impressed you are still maintaining this and serving the community! Big kudos to you!

**Comment by marioney** [comment]
> @marioney Sorry to interrupt but buddy, I'm impressed you are still maintaining this and serving the community! Big kudos to you!

Thanks man!! I've used this up to last year, so I need it to work. Also, seems that people are still using it :)
